# Site
# repository: ParcheKo/parcheko.github.io
repository: sproogen/resume-theme
favicon: images/favicon.png

# Personal info
name: Amir A. Rezaei P.
title: Software Developer
email: amir.a.rezaei.p@gmail.com
phone: '+989399622920'
website: parcheko.ir

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: amir_parcheko
skype_username: amir.a.rezaei.p
github_username:  parcheko
# dribbble_username: jekyll
facebook_username: amir.a.rezaei.p
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: parcheko
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Amir and I'm a software developer. With a vast computer programming and engineering background, problems have always fascinated me to keep solving them in the best and the most correct way I knew at the time.

  I am most skilled in `C#`, `.NET`, `T-SQL` and `Web Security`.

# Skills Section
# skills_title: Skills
# skills_content: |
#   <br/>
#   - Proficient in C#
#   - Proficient in .NET Framework & Core
#   - Proficient in T-SQL (SQL Server)
#   - Proficient in English and technical doc comprehension
#   - Good knowledge of Entity Framework 6 & Core
#   - Solid understanding of Clean Architecture & Domain-Driven Design
#   - Good knowledge of Microservices and related architectural patterns like ES, CQRS etc
#   - Good knowledge of Design Patterns & SOLID Principles
#   - Good knowledge of web security concepts
#   - Experience with RESTful APIs & classic SOAP Web Services
#   - Experience with oAuth / OpenID Connect / Identity Server  
#   - Experience with Git & TFS 
#   - Experience with ASP.NET MVC / Web Forms / Windows Forms
#   - Experience with at CSS/HTML/JavaScript & Angular & TypeScript
#   - Familiar with new Web / Browser Technologies in HTML5, CSS3 & new ECMAScript standards 
#   - Vast experience of Visual Studio, VS Code & debugging
#   - Excellent at Command / Terminal
#   - Familiar with Docker
#   - Familiar with Ionic Framework

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   In my spare time, I also try to play with new and old technologies and create some funny and useful things out of them. Things like:
   - Python for AI and Face Recognition
   - Telegram bots
   - Linux & Terminal
   - Extra bits!
   
   I also like doing calligraphy (
     <span lang="fa">نستعلیق</span>
     ), traveling, playing Ping-Pong and reading about economy if I can create more time :)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme #(Use this is you are hosting your resume yourself)
remote_theme: parcheko/modern-resume-theme #(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
