# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Amir A. Rezaei P.
title: Software Developer
email: amir.a.rezaei.p@gmail.com
website: www.parchecko.ir

# Social links
twitter_username: facespics
github_username:  parcheko
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: parcheko
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Amir and I'm a software developer. With a vast computer programming and engineering background, problems have always fascinated me to keep solving them in the best and the most correct way.

  I am most skilled in `C#/.NET`, `T-SQL` and `Security`

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
   In my spare time, I also try to play with new and old technologies and create some funny and useful things out of them. Among the are:
   - Python for AI and Face Recognition
   - Telegram bots
   - Linux Terminal
   - Extra bits!
   
   I also like doing calligraphy, traveling, playing Ping-Pong and reading about economy if I can  create more time :)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
